language: node_js
node_js:
  - "9"

branches:
  only:
  - master

install:
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  keep-history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master