language: node_js
node_js:
  - "9"

branches:
  only:
  - master

install:
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build
  
deploy:
  provider: pages
  api_key:: "J4CFdtX9LpSIcSZSdWx6nFB6NgxlOjqKvnrgjy2rUzeBKVgQZqUImnjAgNZd5o6rE3NVX0IcwZKFT2gZygLOPJ7YJQDjnmANuZon/o+a14adBnap9EvVqo+FxlzPJEs8Pn/4hoCswFzH/UNauupoxf/lNbI8dWt/rcsW6ngRz9VSIDxycAxtTpGWnYOVmjno7FdZOXc1ing72p02xEWT1uIpRtkukLrCV8O88quY9YrmabuNwn43g6oaCG+vr9lL18BwrUwAehFhuI+03Si4V3FNgnJLYv9P7lfUJggMNU7kvVTbxjVczzB0FlnVr3+ONqPkjeG2mMisEW9Zn8O35e1AsKE3QPFkrK8GzkFjamIhDw4FKMtSaGiT7Q8mZiT2/D5qcuu2wlTU5awqdQ5c/jxEZ4zkHBDcC5SPOAIuG06qtpyso1EP/6sVTDVCihyr8xd9yhMvH2SkJ1t8OtKtXSg1T62G2IELjujqkXESxu6Dgw99W9bANnApwhXnKXM+y9yYaLubt7HwldtFb9iiBfI5OwlPlRgLfNHvUygZ7vM0TrWPFY6cd3vZCnELz4fAGb7iNmQHfFtuXkDWL6ioQ7gErnnILj2uStKrBwrhsUyGBc12uhAbnv6SegT5DjKMdkNDx3EcQ6GgFjaw38f1v20RRTeuxKKCndfHTpVnBko="
  keep-history: true
  skip_cleanup: true
  on:
    branch: master
