language: node_js
node_js:
  - "9"

dist: trusty

sudo: false

branches:
  only:
  - master

env:
  global:
    secure: "GwVetyfpzIqT2LfZZfP1rUWCZ966V52HzXVFJEHIFfDBuZLlliwWxX6qEIgVQkyy+XJi4aj4RRbakYtWVlB2qTqbbn5mhAs5i/Q/WFgxwf7nD9BfXs/Qx6lYVu0Ec0Ub8mk8zTlQLfjP5a9fSfIkbS4Y1ZKlLGfEfZ7EQ829ifIA/FuBv3bm0vqh3BtOTTVvQhM/SEHh6kdT+i25de/+vXWqHH9eXD1ZLpNhsl/G3nTQPB6xMvrG25g96zwQ+/2DV/0i4+7fji4+7HvR8DKxlMV72rAPIyXCAE/3n80GYbDWksAsx2pmEC9QfvqiDKdBUd6rOX6BWt7lpHQZOGOV/lKlzLwnIbrOvdoHt7+U0CRQzxUE8sKyyev66ulm1lZhhUrv6fzNzxhCzAVccFsw9E24Mf/Mr2IZip19j1IrmCFoIoFA0f6skZ3yNjfo6pGLHtR/I/QJssZorOrUHD3yuspURgw+lJ3ypKVvwJdrrqq0h7sllL1v5Ora0zaWw+IH4zHwDuogwrW8s92T7sJ5IAlGVH1uSvI85wBTLI+PSe4xm12cAqawWUL8kFnvyDYAYHMKazCxFmUYShHItTQrxKzEtptEGxVrqnj8iRPMdDHlVbPTpfoNtZE9FGVssmccRrSUpgGF+i2LwmAdjHxkTl874YwPdT2suiSnv9qYUpY="

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - npm i

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
