language: node_js
node_js:
  - "9"

branches:
  only:
  - master

install:
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
